# Global Values
repoUrl: 'https://github.com/nestoras/argocd.git'
targetRevision: HEAD
region: ''
account: ''
clusterName: ''
destinationServer: ''
argoNamespace: ''
argoProject: ''


# Argo Rollout Values
argoRollouts:
  enable: false

awsCloudWatchMetrics:
  enable: false
  serviceAccountName:

awsLoadBalancerController:
  enable: false
  serviceAccountName:
  podDisruptionBudget:
    maxUnavailable: 1
  respectIgnoreDifferences: true
  ignoreDifferences:
    - group: ""
      kind: "Secret"
      jsonPointers:
        - /data
    - group: "admissionregistration.k8s.io"
      kind: "MutatingWebhookConfiguration"
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    - group: "admissionregistration.k8s.io"
      kind: "ValidatingWebhookConfiguration"
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'

awsNodeTerminationHandler:
  enable: false

awsForFluentBit:
  enable: false
  logGroupName:
  serviceAccountName:

calico:
  enable: false
  installation:
  kubernetesProvider: "EKS"

externalDns:
  enable: false
  serviceAccountName:
  zoneIdFilter:

externalSecrets:
  enable: false

karpenter:
  enable: false
  serviceAccountName:
  controllerClusterEndpoint:
  awsDefaultInstanceProfile:

grafana:
  enable: false

metricsServer:
  enable: false

prometheus:
  enable: false
  createNamespace: true
  serviceAccountName:
  roleArn:
  ampWorkspaceUrl:

promtheusNodeExporter:
  enable: false
  serviceAccountName: