apiVersion: v2
name: argo-rollouts
description: A Helm chart for Argo Rollouts
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: argo-rollouts
  version: 2.16.0
  repository: https://argoproj.github.io/argo-helm