apiVersion: v2
name: ingress-nginx
description: A Helm chart for External DNS
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: external-dns
    version: 6.14.3
    repository: https://charts.bitnami.com/bitnami
