apiVersion: v2
name: prometheus
description: A Helm chart for Prometheus
type: application
version: 0.1.1
appVersion: "1.0"

dependencies:
  - name: prometheus
    version: 15.10.1
    repository: https://prometheus-community.github.io/helm-charts