grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:479493230127:certificate/ec091358-4fb1-4bce-9637-b9a135f17eb1
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
      external-dns.alpha.kubernetes.io/hostname: grafana.private.mgmt.narrator.ai
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
    hosts:
      - grafana.private.mgmt.narrator.ai
    path: /
    extraPaths:
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: response-metrics-private
            port:
              name: use-annotation
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
  service:
    type: NodePort

