apiVersion: v2
name: karpenter
description: A Helm chart for Karpenter Autoscaler
type: application
version: 0.3.0
appVersion: '1.0'

dependencies:
  - name: karpenter
    version: 0.16.1
    repository: https://charts.karpenter.sh